repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4  # Используйте актуальную версию Ruff
    hooks:
      - id: ruff
        args: ["--fix", "."]  # Проверять все файлы в проекте