services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FIELD_ENCRYPTION_KEY=${FIELD_ENCRYPTION_KEY}
      - DJANGO_SETTINGS_MODULE=bot_constructor.settings
      - REDIS_URL=redis://redis:6379/0
      - DB_NAME=${DB_NAME:-bots_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-secure_password_123}
      - DB_HOST=db
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A bot_constructor worker -l info -Q bot_operations
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - FIELD_ENCRYPTION_KEY=${FIELD_ENCRYPTION_KEY}
      - DJANGO_SETTINGS_MODULE=src.bot_constructor.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A bot_constructor beat -l info
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
      - FIELD_ENCRYPTION_KEY=${FIELD_ENCRYPTION_KEY}
      - DJANGO_SETTINGS_MODULE=src.bot_constructor.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME:-bots_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secure_password_123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  redis_data:
  postgres_data: