services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=bot_constructor.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A project worker -l info -Q bot_operations
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=src.bot_constructor.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A project beat -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=bot_constructor.settings
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

volumes:
  redis_data:
  postgres_data: