# Generated by Django 5.2.4 on 2025-08-03 14:34

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="gpt_api_key",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True, verbose_name="API ключ"
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="активен"
            ),
        ),
    ]
