# Generated by Django 5.2.4 on 2025-09-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="handler_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки для хендлеров"
            ),
        ),
    ]
