# Generated by Django 5.2.4 on 2025-09-04 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_alter_bot_gpt_api_key_alter_bot_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="on_state",
            field=models.CharField(
                blank=True, default="", verbose_name="Вызывающее состояние"
            ),
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="default_state",
        ),
        migrations.RemoveField(
            model_name="step",
            name="extra_context",
        ),
        migrations.AddField(
            model_name="bot",
            name="ai_model",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ai модель"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="is_running",
            field=models.BooleanField(default=False, verbose_name="запущен"),
        ),
        migrations.AddField(
            model_name="bot",
            name="last_started",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время запуска"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="last_stopped",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время остановки"
            ),
        ),
        migrations.AddField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[("CS", "Conversation")],
                default="CS",
                max_length=2,
                verbose_name="Тип сценария",
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="handler_data",
            field=models.JSONField(
                default=dict, verbose_name="Настройки для хендлеров"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="step",
            name="is_end",
            field=models.BooleanField(default=False, verbose_name="Конец разговора"),
        ),
        migrations.AddField(
            model_name="step",
            name="is_entry_point",
            field=models.BooleanField(default=False, verbose_name="Точка входа"),
        ),
        migrations.AddField(
            model_name="step",
            name="is_fallback",
            field=models.BooleanField(default=False, verbose_name="шаг по умолчанию"),
        ),
        migrations.AddField(
            model_name="step",
            name="is_using_ai",
            field=models.BooleanField(
                default=False, verbose_name="Использование запроса к AI"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст сообщения"
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="priority",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Приоритет"),
        ),
        migrations.AddField(
            model_name="step",
            name="result_state",
            field=models.CharField(
                blank=True, default="", verbose_name="Выходное сотояние"
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="current_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bots",
                to="bots.scenario",
                verbose_name="текущий сценарий",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="gpt_api_url",
            field=models.CharField(
                choices=[
                    ("https://api.deepseek.com", "deepseek"),
                    ("https://api.openai.com", "openai"),
                    ("https://openrouter.ai/api/v1", "openrouter"),
                ],
                default="https://api.deepseek.com",
                max_length=200,
                verbose_name="API GPT URL",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активен"),
        ),
        migrations.AlterField(
            model_name="bot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="bots.scenario",
                verbose_name="сценарий",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="template",
            field=models.CharField(
                choices=[
                    ("ST", "start"),
                    ("CL", "clear"),
                    ("HL", "help"),
                    ("SP", "stop"),
                    ("CC", "custom command"),
                    ("QU", "question"),
                ],
                default="QU",
                max_length=2,
                verbose_name="Шаблон",
            ),
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
