# Generated by Django 5.2.4 on 2025-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0003_alter_scenario_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="scenario_type",
            field=models.CharField(
                choices=[("CS", "Conversation")],
                default="CS",
                help_text="Тип сценария определяет алгоритм конвертации шагов в код.'CS' (CONVERSATION) это алгоритм на основе telegram.ext.ConversationHandler.",
                max_length=2,
                verbose_name="Тип сценария",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="handler_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Формат данных - словарь \n        {"keyboard": list[list[str]], "system": str, "context": str, "command": str, "filter_regex": str}. \n        Все ключи необязательны, лишние ключи игнорируются. \n        - keyboard: список кнопок в клавиатуре,\n        - system: системный промпт для AI модели,\n        - context: дополнительные данные для анализа при обращении к AI,\n        - filter_regex: регулярное выражение для фильтрации хэндлера телеграм,\n        - command: команда, вызывающая соответствующий хэндлер.',
                verbose_name="Настройки для хендлеров",
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="is_fallback",
            field=models.BooleanField(default=False, verbose_name="Шаг по умолчанию"),
        ),
    ]
